chartName: greeting-app

deployment: 
  replicaCount: 1
  image: k3d-testkube-registry:6000/greeter
  tag: latest

config:
  port: 8090 #should be the same as deployment port
  greeting: Hello you bastard

ingress:
  rule: PathPrefix(`/`)
