name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ../../app/docker
          # Note: tags has to be all lower-case
          tags: |
            k3d-testkube-registry:6000/greeter:latest
          # build on feature branches, push only on main branch
          push: k3d-testkube-registry:6000/greeter:latest
          # push: ${{ github.ref == 'refs/heads/main' }}