name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build image and push to local Registry
        run: |
          docker build -t k3d-testkube-registry:6000/greeter:latest app
          docker push k3d-testkube-registry:6000/greeter:latest
        shell: bash
